"""Données de démonstration réalistes pour le secteur CHR en Île-de-France.

Chaque entrée fournit les champs "bruts". Le score, l'explication du score,
le canal recommandé et son explication sont calculés au moment du seed par les
services dédiés (scoring, channel_recommendation), pour rester cohérents.

Les dates de détection sont exprimées en "days_ago" pour que la démo paraisse
toujours fraîche, quel que soit le jour où le seed est lancé.
"""
from typing import List, TypedDict


class DemoLead(TypedDict, total=False):
    establishment_name: str
    establishment_type: str
    city: str
    address: str
    main_signal: str
    secondary_signals: List[str]
    days_ago: int
    estimated_timing: str
    probable_needs: List[str]
    decision_maker: str
    proof_text: str
    proof_url: str
    status: str
    has_social: bool
    next_follow_up_in: int  # jours avant relance (optionnel)


DEMO_LEADS: List[DemoLead] = [
    # --- Les 8 exemples demandés ---------------------------------------------
    {
        "establishment_name": "Maison Oria",
        "establishment_type": "restaurant",
        "city": "Massy",
        "address": "14 avenue du Président Allende, 91300 Massy",
        "main_signal": "ouverture prochaine",
        "secondary_signals": ["recrutement", "compte instagram récent"],
        "days_ago": 8,
        "estimated_timing": "J-60",
        "probable_needs": ["luminaires de salle", "mobilier de restaurant", "éclairage d'ambiance"],
        "decision_maker": "Sarah Oria, gérante",
        "proof_text": "Annonce d'ouverture d'un restaurant méditerranéen + offre d'emploi serveur publiée sur une page locale.",
        "proof_url": "https://example.com/massy/maison-oria-ouverture",
        "status": "non_contacte",
        "has_social": True,
    },
    {
        "establishment_name": "Café Lumo",
        "establishment_type": "coffee shop",
        "city": "Boulogne-Billancourt",
        "address": "27 rue de Billancourt, 92100 Boulogne-Billancourt",
        "main_signal": "travaux visibles",
        "secondary_signals": ["ouverture prochaine", "compte instagram récent"],
        "days_ago": 5,
        "estimated_timing": "J-30",
        "probable_needs": ["suspensions design", "éclairage comptoir", "mobilier de coffee shop"],
        "decision_maker": "Thomas Lemaire, fondateur",
        "proof_text": "Devanture en travaux + compte Instagram créé récemment annonçant un coffee shop.",
        "proof_url": "https://instagram.com/cafelumo",
        "status": "non_contacte",
        "has_social": True,
    },
    {
        "establishment_name": "Hôtel Rivage",
        "establishment_type": "hôtel",
        "city": "Vincennes",
        "address": "3 avenue de Paris, 94300 Vincennes",
        "main_signal": "rénovation",
        "secondary_signals": ["recrutement"],
        "days_ago": 18,
        "estimated_timing": "J-90",
        "probable_needs": ["éclairage lobby", "mobilier d'accueil", "appliques de couloir"],
        "decision_maker": "Direction de l'établissement",
        "proof_text": "Rénovation du lobby annoncée + offre de réceptionniste publiée.",
        "proof_url": "https://example.com/vincennes/hotel-rivage-renovation",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Brasserie Saint-Pierre",
        "establishment_type": "brasserie",
        "city": "Versailles",
        "address": "9 rue de la Paroisse, 78000 Versailles",
        "main_signal": "reprise",
        "secondary_signals": ["changement propriétaire", "annonce presse locale"],
        "days_ago": 22,
        "estimated_timing": "J-60",
        "probable_needs": ["réagencement", "luminaires de salle", "mobilier de terrasse"],
        "decision_maker": "Nouveau propriétaire (repreneur)",
        "proof_text": "Annonce légale de cession de fonds de commerce + article local sur la reprise.",
        "proof_url": "https://example.com/versailles/brasserie-saint-pierre-reprise",
        "status": "contacte",
        "has_social": False,
        "next_follow_up_in": 4,
    },
    {
        "establishment_name": "Atelier Bao",
        "establishment_type": "restaurant",
        "city": "Paris",
        "address": "52 rue du Faubourg Saint-Denis, 75010 Paris",
        "main_signal": "ouverture prochaine",
        "secondary_signals": ["recrutement", "compte instagram récent"],
        "days_ago": 11,
        "estimated_timing": "J-45",
        "probable_needs": ["éclairage d'ambiance", "mobilier de salle", "suspensions"],
        "decision_maker": "Chef-propriétaire",
        "proof_text": "Ouverture d'un restaurant asiatique annoncée + recherche d'un chef de partie.",
        "proof_url": "https://instagram.com/atelierbao",
        "status": "non_contacte",
        "has_social": True,
    },
    {
        "establishment_name": "Le Comptoir d'Antony",
        "establishment_type": "bar",
        "city": "Antony",
        "address": "18 rue Auguste Mounié, 92160 Antony",
        "main_signal": "changement propriétaire",
        "secondary_signals": ["nouveau point de vente"],
        "days_ago": 30,
        "estimated_timing": "J-60",
        "probable_needs": ["éclairage de bar", "mobilier", "enseigne lumineuse"],
        "decision_maker": "Nouveau gérant",
        "proof_text": "Changement de propriétaire et nouveau concept de bar à cocktails annoncé.",
        "proof_url": "https://example.com/antony/le-comptoir-nouveau-concept",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Nova Traiteur",
        "establishment_type": "traiteur",
        "city": "Créteil",
        "address": "6 rue du Général Leclerc, 94000 Créteil",
        "main_signal": "création récente",
        "secondary_signals": ["nouveau point de vente"],
        "days_ago": 14,
        "estimated_timing": "J-30",
        "probable_needs": ["éclairage de laboratoire", "mobilier de présentation", "signalétique"],
        "decision_maker": "Fondateur",
        "proof_text": "Création récente d'une société de traiteur, recherche d'un local commercial.",
        "proof_url": "https://example.com/creteil/nova-traiteur-creation",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Mareva Hôtel",
        "establishment_type": "hôtel",
        "city": "Levallois-Perret",
        "address": "21 rue Aristide Briand, 92300 Levallois-Perret",
        "main_signal": "rénovation",
        "secondary_signals": ["changement propriétaire"],
        "days_ago": 26,
        "estimated_timing": "J-90",
        "probable_needs": ["éclairage chambres", "mobilier de chambre", "appliques"],
        "decision_maker": "Nouveau directeur d'établissement",
        "proof_text": "Rénovation des chambres en cours + arrivée d'un nouveau directeur.",
        "proof_url": "https://example.com/levallois/mareva-hotel-renovation",
        "status": "contacte",
        "has_social": False,
        "next_follow_up_in": 6,
    },

    # --- Leads supplémentaires ------------------------------------------------
    {
        "establishment_name": "Le Petit Versaillais",
        "establishment_type": "restaurant",
        "city": "Versailles",
        "address": "44 rue de Satory, 78000 Versailles",
        "main_signal": "ouverture prochaine",
        "secondary_signals": ["travaux visibles"],
        "days_ago": 9,
        "estimated_timing": "J-45",
        "probable_needs": ["luminaires de salle", "mobilier de terrasse"],
        "decision_maker": "Gérant",
        "proof_text": "Permis de travaux affiché en devanture annonçant un restaurant traditionnel.",
        "proof_url": "https://example.com/versailles/petit-versaillais",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Brew & Co",
        "establishment_type": "coffee shop",
        "city": "Montreuil",
        "address": "12 rue de Paris, 93100 Montreuil",
        "main_signal": "création récente",
        "secondary_signals": ["compte instagram récent", "ouverture prochaine"],
        "days_ago": 6,
        "estimated_timing": "J-30",
        "probable_needs": ["suspensions design", "éclairage comptoir"],
        "decision_maker": "Camille Roy, fondatrice",
        "proof_text": "Société créée le mois dernier, teasing d'ouverture sur Instagram.",
        "proof_url": "https://instagram.com/brewandco.mtl",
        "status": "non_contacte",
        "has_social": True,
    },
    {
        "establishment_name": "Trattoria Bella",
        "establishment_type": "restaurant",
        "city": "Saint-Maur-des-Fossés",
        "address": "30 avenue de la République, 94100 Saint-Maur-des-Fossés",
        "main_signal": "reprise",
        "secondary_signals": ["rénovation"],
        "days_ago": 35,
        "estimated_timing": "J-60",
        "probable_needs": ["réagencement", "éclairage d'ambiance", "mobilier"],
        "decision_maker": "Repreneur",
        "proof_text": "Cession de fonds annoncée, rénovation de la salle prévue.",
        "proof_url": "https://example.com/saint-maur/trattoria-bella",
        "status": "relance",
        "has_social": False,
        "next_follow_up_in": 2,
    },
    {
        "establishment_name": "Hôtel des Lices",
        "establishment_type": "hôtel",
        "city": "Issy-les-Moulineaux",
        "address": "8 rue du Général Leclerc, 92130 Issy-les-Moulineaux",
        "main_signal": "expansion",
        "secondary_signals": ["nouveau point de vente"],
        "days_ago": 40,
        "estimated_timing": "J-90",
        "probable_needs": ["éclairage lobby", "mobilier d'accueil", "signalétique"],
        "decision_maker": "Directeur général",
        "proof_text": "Annonce d'ouverture d'un second établissement du groupe.",
        "proof_url": "https://example.com/issy/hotel-des-lices-expansion",
        "status": "interesse",
        "has_social": False,
        "next_follow_up_in": 3,
    },
    {
        "establishment_name": "Bar Le Onze",
        "establishment_type": "bar",
        "city": "Courbevoie",
        "address": "11 rue de Bezons, 92400 Courbevoie",
        "main_signal": "changement propriétaire",
        "secondary_signals": ["annonce presse locale"],
        "days_ago": 28,
        "estimated_timing": "J-60",
        "probable_needs": ["éclairage de bar", "enseigne lumineuse"],
        "decision_maker": "Nouveau gérant",
        "proof_text": "Article de presse locale sur le rachat du bar par un nouveau propriétaire.",
        "proof_url": "https://example.com/courbevoie/bar-le-onze",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Sushi Yuzu",
        "establishment_type": "restaurant",
        "city": "Neuilly-sur-Seine",
        "address": "5 avenue Charles de Gaulle, 92200 Neuilly-sur-Seine",
        "main_signal": "ouverture prochaine",
        "secondary_signals": ["recrutement", "compte instagram récent"],
        "days_ago": 12,
        "estimated_timing": "J-45",
        "probable_needs": ["éclairage d'ambiance", "mobilier de salle"],
        "decision_maker": "Kenji Tanaka, gérant",
        "proof_text": "Annonce d'ouverture d'un restaurant japonais + recrutement de commis.",
        "proof_url": "https://instagram.com/sushiyuzu.neuilly",
        "status": "non_contacte",
        "has_social": True,
    },
    {
        "establishment_name": "La Cave d'Évry",
        "establishment_type": "bar",
        "city": "Évry-Courcouronnes",
        "address": "2 cours Blaise Pascal, 91000 Évry-Courcouronnes",
        "main_signal": "rénovation",
        "secondary_signals": ["travaux visibles"],
        "days_ago": 20,
        "estimated_timing": "J-60",
        "probable_needs": ["éclairage d'ambiance", "mobilier", "décoration"],
        "decision_maker": "Propriétaire",
        "proof_text": "Travaux de rénovation visibles, réouverture annoncée.",
        "proof_url": "https://example.com/evry/la-cave",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Le Jardin de Palaiseau",
        "establishment_type": "restaurant",
        "city": "Palaiseau",
        "address": "16 rue de Paris, 91120 Palaiseau",
        "main_signal": "ouverture prochaine",
        "secondary_signals": ["recrutement"],
        "days_ago": 16,
        "estimated_timing": "J-60",
        "probable_needs": ["mobilier de terrasse", "luminaires extérieurs"],
        "decision_maker": "Gérante",
        "proof_text": "Ouverture d'un restaurant avec terrasse + recherche de personnel de salle.",
        "proof_url": "https://example.com/palaiseau/jardin",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Coffee Spot",
        "establishment_type": "coffee shop",
        "city": "Paris",
        "address": "120 rue Oberkampf, 75011 Paris",
        "main_signal": "nouveau point de vente",
        "secondary_signals": ["compte instagram récent", "expansion"],
        "days_ago": 7,
        "estimated_timing": "J-30",
        "probable_needs": ["suspensions design", "éclairage comptoir", "mobilier"],
        "decision_maker": "Responsable développement",
        "proof_text": "Ouverture d'un nouveau point de vente d'une enseigne de coffee shop.",
        "proof_url": "https://instagram.com/coffeespot.paris",
        "status": "non_contacte",
        "has_social": True,
    },
    {
        "establishment_name": "Brasserie du Marché",
        "establishment_type": "brasserie",
        "city": "Antony",
        "address": "3 place du Marché, 92160 Antony",
        "main_signal": "reprise",
        "secondary_signals": ["changement propriétaire"],
        "days_ago": 33,
        "estimated_timing": "J-60",
        "probable_needs": ["réagencement", "luminaires de salle"],
        "decision_maker": "Repreneur",
        "proof_text": "Reprise du fonds de commerce, réouverture sous nouvelle enseigne.",
        "proof_url": "https://example.com/antony/brasserie-du-marche",
        "status": "contacte",
        "has_social": False,
        "next_follow_up_in": 5,
    },
    {
        "establishment_name": "Hôtel Belair",
        "establishment_type": "hôtel",
        "city": "Créteil",
        "address": "40 avenue de Verdun, 94000 Créteil",
        "main_signal": "rénovation",
        "secondary_signals": ["recrutement"],
        "days_ago": 45,
        "estimated_timing": "J-90",
        "probable_needs": ["éclairage chambres", "mobilier de chambre"],
        "decision_maker": "Direction",
        "proof_text": "Plan de rénovation des chambres communiqué + recrutement de personnel.",
        "proof_url": "https://example.com/creteil/hotel-belair",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Pizza Forno",
        "establishment_type": "restaurant",
        "city": "Vincennes",
        "address": "22 rue de Montreuil, 94300 Vincennes",
        "main_signal": "ouverture prochaine",
        "secondary_signals": ["travaux visibles", "compte instagram récent"],
        "days_ago": 4,
        "estimated_timing": "J-30",
        "probable_needs": ["éclairage comptoir", "mobilier", "enseigne lumineuse"],
        "decision_maker": "Gérant",
        "proof_text": "Devanture en travaux, compte Instagram annonçant une pizzeria.",
        "proof_url": "https://instagram.com/pizzaforno.vincennes",
        "status": "non_contacte",
        "has_social": True,
    },
    {
        "establishment_name": "Le Bistrot des Halles",
        "establishment_type": "restaurant",
        "city": "Levallois-Perret",
        "address": "7 rue Voltaire, 92300 Levallois-Perret",
        "main_signal": "changement propriétaire",
        "secondary_signals": ["rénovation"],
        "days_ago": 38,
        "estimated_timing": "J-60",
        "probable_needs": ["réagencement", "éclairage d'ambiance"],
        "decision_maker": "Nouveau propriétaire",
        "proof_text": "Changement de propriétaire enregistré, rénovation de la salle annoncée.",
        "proof_url": "https://example.com/levallois/bistrot-des-halles",
        "status": "perdu",
        "has_social": False,
    },
    {
        "establishment_name": "Green Bowl",
        "establishment_type": "restaurant",
        "city": "Issy-les-Moulineaux",
        "address": "14 rue du Gouverneur Général Éboué, 92130 Issy-les-Moulineaux",
        "main_signal": "création récente",
        "secondary_signals": ["ouverture prochaine", "compte instagram récent"],
        "days_ago": 10,
        "estimated_timing": "J-45",
        "probable_needs": ["éclairage de salle", "mobilier", "signalétique"],
        "decision_maker": "Fondateur",
        "proof_text": "Restaurant healthy nouvellement créé, ouverture en préparation.",
        "proof_url": "https://instagram.com/greenbowl.issy",
        "status": "non_contacte",
        "has_social": True,
    },
    {
        "establishment_name": "Le Refuge",
        "establishment_type": "bar",
        "city": "Montreuil",
        "address": "55 rue de la Révolution, 93100 Montreuil",
        "main_signal": "rénovation",
        "secondary_signals": ["travaux visibles"],
        "days_ago": 24,
        "estimated_timing": "J-60",
        "probable_needs": ["éclairage d'ambiance", "mobilier", "décoration"],
        "decision_maker": "Propriétaire",
        "proof_text": "Bar fermé pour rénovation, réouverture annoncée prochainement.",
        "proof_url": "https://example.com/montreuil/le-refuge",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Maison Doré Traiteur",
        "establishment_type": "traiteur",
        "city": "Boulogne-Billancourt",
        "address": "63 route de la Reine, 92100 Boulogne-Billancourt",
        "main_signal": "expansion",
        "secondary_signals": ["recrutement"],
        "days_ago": 50,
        "estimated_timing": "J-90",
        "probable_needs": ["mobilier de présentation", "éclairage de boutique"],
        "decision_maker": "Dirigeant",
        "proof_text": "Ouverture d'un nouveau laboratoire + recrutements multiples.",
        "proof_url": "https://example.com/boulogne/maison-dore",
        "status": "contacte",
        "has_social": False,
        "next_follow_up_in": 7,
    },
    {
        "establishment_name": "Café de la Gare",
        "establishment_type": "café",
        "city": "Massy",
        "address": "1 place de la Gare, 91300 Massy",
        "main_signal": "reprise",
        "secondary_signals": ["changement propriétaire", "rénovation"],
        "days_ago": 19,
        "estimated_timing": "J-45",
        "probable_needs": ["réagencement", "luminaires de salle", "mobilier de terrasse"],
        "decision_maker": "Repreneur",
        "proof_text": "Reprise du café historique de la gare, rénovation complète prévue.",
        "proof_url": "https://example.com/massy/cafe-de-la-gare",
        "status": "interesse",
        "has_social": False,
        "next_follow_up_in": 2,
    },
    {
        "establishment_name": "Le Versailles Royal",
        "establishment_type": "hôtel",
        "city": "Versailles",
        "address": "12 avenue de Sceaux, 78000 Versailles",
        "main_signal": "rénovation",
        "secondary_signals": ["expansion"],
        "days_ago": 60,
        "estimated_timing": "J-90",
        "probable_needs": ["éclairage lobby", "mobilier d'accueil", "appliques de couloir"],
        "decision_maker": "Directrice d'établissement",
        "proof_text": "Programme de rénovation pluriannuel annoncé pour l'établissement.",
        "proof_url": "https://example.com/versailles/versailles-royal",
        "status": "rdv",
        "has_social": False,
        "next_follow_up_in": 1,
    },
    {
        "establishment_name": "Tacos Loco",
        "establishment_type": "restaurant",
        "city": "Évry-Courcouronnes",
        "address": "33 boulevard de l'Europe, 91000 Évry-Courcouronnes",
        "main_signal": "ouverture prochaine",
        "secondary_signals": ["compte instagram récent"],
        "days_ago": 13,
        "estimated_timing": "J-45",
        "probable_needs": ["éclairage comptoir", "mobilier", "enseigne lumineuse"],
        "decision_maker": "Gérant",
        "proof_text": "Ouverture annoncée d'un fast-food mexicain, compte Instagram actif.",
        "proof_url": "https://instagram.com/tacosloco.evry",
        "status": "non_contacte",
        "has_social": True,
    },
    {
        "establishment_name": "Le Comptoir Courbevoie",
        "establishment_type": "café",
        "city": "Courbevoie",
        "address": "8 rue Victor Hugo, 92400 Courbevoie",
        "main_signal": "création récente",
        "secondary_signals": ["ouverture prochaine"],
        "days_ago": 17,
        "estimated_timing": "J-60",
        "probable_needs": ["luminaires de salle", "mobilier de terrasse"],
        "decision_maker": "Fondatrice",
        "proof_text": "Société de café-restaurant nouvellement immatriculée.",
        "proof_url": "https://example.com/courbevoie/le-comptoir",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Brasserie Le Lion",
        "establishment_type": "brasserie",
        "city": "Saint-Maur-des-Fossés",
        "address": "76 avenue Foch, 94100 Saint-Maur-des-Fossés",
        "main_signal": "changement propriétaire",
        "secondary_signals": ["annonce presse locale", "rénovation"],
        "days_ago": 29,
        "estimated_timing": "J-60",
        "probable_needs": ["réagencement", "éclairage d'ambiance", "mobilier"],
        "decision_maker": "Nouveau propriétaire",
        "proof_text": "Rachat de la brasserie, annonce dans la presse locale, rénovation en vue.",
        "proof_url": "https://example.com/saint-maur/brasserie-le-lion",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Hôtel Antony Park",
        "establishment_type": "hôtel",
        "city": "Antony",
        "address": "2 rue des Sources, 92160 Antony",
        "main_signal": "ouverture prochaine",
        "secondary_signals": ["recrutement"],
        "days_ago": 21,
        "estimated_timing": "J-90",
        "probable_needs": ["éclairage chambres", "mobilier d'accueil", "appliques"],
        "decision_maker": "Directeur",
        "proof_text": "Ouverture d'un hôtel d'affaires annoncée + recrutement de plusieurs postes.",
        "proof_url": "https://example.com/antony/hotel-park",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Pasta e Basta",
        "establishment_type": "restaurant",
        "city": "Vincennes",
        "address": "9 rue Robert Giraudineau, 94300 Vincennes",
        "main_signal": "reprise",
        "secondary_signals": ["rénovation"],
        "days_ago": 41,
        "estimated_timing": "J-60",
        "probable_needs": ["réagencement", "luminaires de salle"],
        "decision_maker": "Repreneur",
        "proof_text": "Cession de fonds, repositionnement en restaurant italien.",
        "proof_url": "https://example.com/vincennes/pasta-e-basta",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Le Spot Burger",
        "establishment_type": "restaurant",
        "city": "Paris",
        "address": "200 rue de Charenton, 75012 Paris",
        "main_signal": "nouveau point de vente",
        "secondary_signals": ["recrutement", "compte instagram récent"],
        "days_ago": 6,
        "estimated_timing": "J-30",
        "probable_needs": ["éclairage comptoir", "mobilier", "enseigne lumineuse"],
        "decision_maker": "Responsable réseau",
        "proof_text": "Nouveau point de vente d'une chaîne de burgers, recrutement en cours.",
        "proof_url": "https://instagram.com/lespotburger",
        "status": "non_contacte",
        "has_social": True,
    },
    {
        "establishment_name": "Café Néo",
        "establishment_type": "café",
        "city": "Palaiseau",
        "address": "5 rue de l'Effort Mutuel, 91120 Palaiseau",
        "main_signal": "travaux visibles",
        "secondary_signals": ["ouverture prochaine"],
        "days_ago": 9,
        "estimated_timing": "J-45",
        "probable_needs": ["suspensions", "éclairage comptoir", "mobilier"],
        "decision_maker": "Gérant",
        "proof_text": "Local en travaux, panneau annonçant un café de spécialité.",
        "proof_url": "https://example.com/palaiseau/cafe-neo",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Le Bouchon Lyonnais",
        "establishment_type": "restaurant",
        "city": "Neuilly-sur-Seine",
        "address": "30 rue de Chartres, 92200 Neuilly-sur-Seine",
        "main_signal": "rénovation",
        "secondary_signals": ["annonce presse locale"],
        "days_ago": 55,
        "estimated_timing": "J-90",
        "probable_needs": ["éclairage d'ambiance", "mobilier de salle"],
        "decision_maker": "Propriétaire",
        "proof_text": "Article local annonçant la rénovation d'un bouchon réputé.",
        "proof_url": "https://example.com/neuilly/bouchon-lyonnais",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Saveurs d'Asie",
        "establishment_type": "traiteur",
        "city": "Montreuil",
        "address": "88 rue de Vincennes, 93100 Montreuil",
        "main_signal": "création récente",
        "secondary_signals": ["nouveau point de vente"],
        "days_ago": 15,
        "estimated_timing": "J-30",
        "probable_needs": ["éclairage de boutique", "mobilier de présentation"],
        "decision_maker": "Fondateur",
        "proof_text": "Traiteur asiatique récemment créé, ouverture d'une boutique.",
        "proof_url": "https://example.com/montreuil/saveurs-asie",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Hôtel Le Massy",
        "establishment_type": "hôtel",
        "city": "Massy",
        "address": "10 place de France, 91300 Massy",
        "main_signal": "expansion",
        "secondary_signals": ["recrutement", "nouveau point de vente"],
        "days_ago": 47,
        "estimated_timing": "J-90",
        "probable_needs": ["éclairage lobby", "mobilier d'accueil", "signalétique"],
        "decision_maker": "Directeur des opérations",
        "proof_text": "Le groupe hôtelier annonce un nouvel établissement près de la gare TGV.",
        "proof_url": "https://example.com/massy/hotel-le-massy",
        "status": "interesse",
        "has_social": False,
        "next_follow_up_in": 4,
    },
    {
        "establishment_name": "Le Bar à Vin",
        "establishment_type": "bar",
        "city": "Boulogne-Billancourt",
        "address": "9 rue de l'Ancienne Mairie, 92100 Boulogne-Billancourt",
        "main_signal": "ouverture prochaine",
        "secondary_signals": ["compte instagram récent", "travaux visibles"],
        "days_ago": 8,
        "estimated_timing": "J-45",
        "probable_needs": ["éclairage d'ambiance", "mobilier", "casiers à vin lumineux"],
        "decision_maker": "Gérant",
        "proof_text": "Travaux d'un futur bar à vin, teasing sur Instagram.",
        "proof_url": "https://instagram.com/lebaravin.boulogne",
        "status": "non_contacte",
        "has_social": True,
    },
    {
        "establishment_name": "Crêperie Bréizh",
        "establishment_type": "restaurant",
        "city": "Saint-Maur-des-Fossés",
        "address": "21 avenue Joffre, 94100 Saint-Maur-des-Fossés",
        "main_signal": "ouverture prochaine",
        "secondary_signals": ["recrutement"],
        "days_ago": 12,
        "estimated_timing": "J-60",
        "probable_needs": ["luminaires de salle", "mobilier"],
        "decision_maker": "Gérante",
        "proof_text": "Ouverture d'une crêperie annoncée + offre de crêpier.",
        "proof_url": "https://example.com/saint-maur/creperie-breizh",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Urban Coffee",
        "establishment_type": "coffee shop",
        "city": "Courbevoie",
        "address": "1 parvis de la Défense, 92400 Courbevoie",
        "main_signal": "nouveau point de vente",
        "secondary_signals": ["expansion", "compte instagram récent"],
        "days_ago": 5,
        "estimated_timing": "J-30",
        "probable_needs": ["suspensions design", "éclairage comptoir", "mobilier"],
        "decision_maker": "Responsable développement réseau",
        "proof_text": "Nouveau point de vente d'une enseigne de coffee shop dans le quartier d'affaires.",
        "proof_url": "https://instagram.com/urbancoffee.ladefense",
        "status": "non_contacte",
        "has_social": True,
    },
    {
        "establishment_name": "Le Vincennois",
        "establishment_type": "brasserie",
        "city": "Vincennes",
        "address": "4 cours Marigny, 94300 Vincennes",
        "main_signal": "reprise",
        "secondary_signals": ["changement propriétaire"],
        "days_ago": 27,
        "estimated_timing": "J-60",
        "probable_needs": ["réagencement", "luminaires de salle", "mobilier de terrasse"],
        "decision_maker": "Repreneur",
        "proof_text": "Reprise de la brasserie de centre-ville par un nouvel exploitant.",
        "proof_url": "https://example.com/vincennes/le-vincennois",
        "status": "contacte",
        "has_social": False,
        "next_follow_up_in": 5,
    },
    {
        "establishment_name": "Mama Pasta",
        "establishment_type": "restaurant",
        "city": "Levallois-Perret",
        "address": "55 rue Anatole France, 92300 Levallois-Perret",
        "main_signal": "ouverture prochaine",
        "secondary_signals": ["recrutement", "compte instagram récent"],
        "days_ago": 10,
        "estimated_timing": "J-45",
        "probable_needs": ["éclairage d'ambiance", "mobilier de salle"],
        "decision_maker": "Chef-propriétaire",
        "proof_text": "Ouverture d'un restaurant italien + recrutement de personnel de salle.",
        "proof_url": "https://instagram.com/mamapasta.levallois",
        "status": "non_contacte",
        "has_social": True,
    },
    {
        "establishment_name": "Le Coffee d'Évry",
        "establishment_type": "café",
        "city": "Évry-Courcouronnes",
        "address": "8 place des Terrasses, 91000 Évry-Courcouronnes",
        "main_signal": "rénovation",
        "secondary_signals": ["travaux visibles"],
        "days_ago": 23,
        "estimated_timing": "J-60",
        "probable_needs": ["luminaires de salle", "mobilier", "décoration"],
        "decision_maker": "Gérant",
        "proof_text": "Café fermé pour rénovation, réaménagement intérieur en cours.",
        "proof_url": "https://example.com/evry/le-coffee",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Bistrot Palaiseau",
        "establishment_type": "restaurant",
        "city": "Palaiseau",
        "address": "12 rue de Paris, 91120 Palaiseau",
        "main_signal": "changement propriétaire",
        "secondary_signals": ["rénovation"],
        "days_ago": 130,
        "estimated_timing": "J-90",
        "probable_needs": ["réagencement", "éclairage d'ambiance"],
        "decision_maker": "Nouveau propriétaire",
        "proof_text": "Changement de propriétaire enregistré il y a plusieurs mois, projet de rénovation lent.",
        "proof_url": "https://example.com/palaiseau/bistrot",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Le Petit Neuilly",
        "establishment_type": "café",
        "city": "Neuilly-sur-Seine",
        "address": "70 avenue du Roule, 92200 Neuilly-sur-Seine",
        "main_signal": "ouverture prochaine",
        "secondary_signals": ["travaux visibles"],
        "days_ago": 7,
        "estimated_timing": "J-30",
        "probable_needs": ["luminaires de salle", "mobilier de terrasse"],
        "decision_maker": "Gérante",
        "proof_text": "Local en travaux, ouverture imminente d'un café de quartier.",
        "proof_url": "https://example.com/neuilly/le-petit-neuilly",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Délices Traiteur",
        "establishment_type": "traiteur",
        "city": "Issy-les-Moulineaux",
        "address": "3 rue Rouget de Lisle, 92130 Issy-les-Moulineaux",
        "main_signal": "expansion",
        "secondary_signals": ["recrutement"],
        "days_ago": 44,
        "estimated_timing": "J-90",
        "probable_needs": ["éclairage de boutique", "mobilier de présentation"],
        "decision_maker": "Dirigeante",
        "proof_text": "Développement d'un second site de production + recrutement.",
        "proof_url": "https://example.com/issy/delices-traiteur",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Le Gaulois",
        "establishment_type": "brasserie",
        "city": "Créteil",
        "address": "1 avenue du Général de Gaulle, 94000 Créteil",
        "main_signal": "rénovation",
        "secondary_signals": ["recrutement", "travaux visibles"],
        "days_ago": 31,
        "estimated_timing": "J-60",
        "probable_needs": ["réagencement", "éclairage d'ambiance", "mobilier de terrasse"],
        "decision_maker": "Propriétaire",
        "proof_text": "Brasserie en rénovation, réouverture annoncée + recrutement de serveurs.",
        "proof_url": "https://example.com/creteil/le-gaulois",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Matcha Bar",
        "establishment_type": "coffee shop",
        "city": "Paris",
        "address": "8 rue de Bretagne, 75003 Paris",
        "main_signal": "création récente",
        "secondary_signals": ["ouverture prochaine", "compte instagram récent"],
        "days_ago": 6,
        "estimated_timing": "J-30",
        "probable_needs": ["suspensions design", "éclairage comptoir", "mobilier"],
        "decision_maker": "Fondatrice",
        "proof_text": "Concept de matcha bar nouvellement créé, forte présence Instagram.",
        "proof_url": "https://instagram.com/matchabar.paris",
        "status": "non_contacte",
        "has_social": True,
    },
    {
        "establishment_name": "Auberge de Montreuil",
        "establishment_type": "hôtel",
        "city": "Montreuil",
        "address": "2 rue de Romainville, 93100 Montreuil",
        "main_signal": "reprise",
        "secondary_signals": ["rénovation", "changement propriétaire"],
        "days_ago": 36,
        "estimated_timing": "J-90",
        "probable_needs": ["éclairage chambres", "mobilier d'accueil", "appliques"],
        "decision_maker": "Repreneur / nouveau directeur",
        "proof_text": "Reprise de l'auberge avec plan de rénovation complet.",
        "proof_url": "https://example.com/montreuil/auberge",
        "status": "gagne",
        "has_social": False,
    },
    {
        "establishment_name": "Burger Factory",
        "establishment_type": "restaurant",
        "city": "Antony",
        "address": "40 avenue de la Division Leclerc, 92160 Antony",
        "main_signal": "nouveau point de vente",
        "secondary_signals": ["recrutement"],
        "days_ago": 11,
        "estimated_timing": "J-45",
        "probable_needs": ["éclairage comptoir", "mobilier", "enseigne lumineuse"],
        "decision_maker": "Responsable réseau",
        "proof_text": "Ouverture d'un nouveau restaurant de la franchise + recrutement.",
        "proof_url": "https://example.com/antony/burger-factory",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Le Comptoir Versailles",
        "establishment_type": "café",
        "city": "Versailles",
        "address": "5 rue Hoche, 78000 Versailles",
        "main_signal": "reprise",
        "secondary_signals": ["changement propriétaire", "rénovation"],
        "days_ago": 25,
        "estimated_timing": "J-60",
        "probable_needs": ["réagencement", "luminaires de salle", "mobilier de terrasse"],
        "decision_maker": "Repreneur",
        "proof_text": "Reprise d'un café-restaurant historique, rénovation programmée.",
        "proof_url": "https://example.com/versailles/le-comptoir",
        "status": "contacte",
        "has_social": False,
        "next_follow_up_in": 3,
    },
    # --- Leads "froids" (signaux anciens / isolés) pour étaler le scoring -----
    {
        "establishment_name": "Le Vieux Comptoir",
        "establishment_type": "café",
        "city": "Créteil",
        "address": "12 rue Juliette Savar, 94000 Créteil",
        "main_signal": "rénovation",
        "secondary_signals": [],
        "days_ago": 150,
        "estimated_timing": "J-90",
        "probable_needs": ["luminaires de salle"],
        "decision_maker": "Propriétaire",
        "proof_text": "Mention d'une rénovation il y a plusieurs mois, sans suite visible depuis.",
        "proof_url": "https://example.com/creteil/vieux-comptoir",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Brasserie de la Mairie",
        "establishment_type": "brasserie",
        "city": "Palaiseau",
        "address": "1 place de la Victoire, 91120 Palaiseau",
        "main_signal": "annonce presse locale",
        "secondary_signals": [],
        "days_ago": 110,
        "estimated_timing": "J-90",
        "probable_needs": ["mobilier de terrasse"],
        "decision_maker": "Gérant",
        "proof_text": "Brève dans la presse locale il y a environ 3-4 mois, signal isolé.",
        "proof_url": "https://example.com/palaiseau/brasserie-mairie",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Snack du Centre",
        "establishment_type": "restaurant",
        "city": "Évry-Courcouronnes",
        "address": "5 place des Droits de l'Homme, 91000 Évry-Courcouronnes",
        "main_signal": "recrutement",
        "secondary_signals": [],
        "days_ago": 135,
        "estimated_timing": "J-90",
        "probable_needs": ["éclairage comptoir"],
        "decision_maker": "Responsable",
        "proof_text": "Ancienne offre d'emploi, signal faible et daté.",
        "proof_url": "https://example.com/evry/snack-du-centre",
        "status": "non_contacte",
        "has_social": False,
    },
    {
        "establishment_name": "Sakura Sushi",
        "establishment_type": "restaurant",
        "city": "Courbevoie",
        "address": "18 rue de l'Industrie, 92400 Courbevoie",
        "main_signal": "ouverture prochaine",
        "secondary_signals": ["compte instagram récent", "recrutement"],
        "days_ago": 9,
        "estimated_timing": "J-45",
        "probable_needs": ["éclairage d'ambiance", "mobilier de salle"],
        "decision_maker": "Gérant",
        "proof_text": "Ouverture d'un restaurant japonais annoncée, recrutement de personnel.",
        "proof_url": "https://instagram.com/sakurasushi.courbevoie",
        "status": "non_contacte",
        "has_social": True,
    },
]
